// Code generated by mockery v2.21.4. DO NOT EDIT.

package mocks

import (
	auth "github.com/rakhmatullahyoga/mini-aspire/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// IAuthUsecase is an autogenerated mock type for the IAuthUsecase type
type IAuthUsecase struct {
	mock.Mock
}

// Login provides a mock function with given fields: username, password
func (_m *IAuthUsecase) Login(username string, password string) (auth.Token, error) {
	ret := _m.Called(username, password)

	var r0 auth.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (auth.Token, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) auth.Token); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Get(0).(auth.Token)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: username, password
func (_m *IAuthUsecase) Register(username string, password string) (auth.Token, error) {
	ret := _m.Called(username, password)

	var r0 auth.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (auth.Token, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) auth.Token); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Get(0).(auth.Token)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIAuthUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewIAuthUsecase creates a new instance of IAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIAuthUsecase(t mockConstructorTestingTNewIAuthUsecase) *IAuthUsecase {
	mock := &IAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
