// Code generated by mockery v2.21.4. DO NOT EDIT.

package mocks

import (
	auth "github.com/rakhmatullahyoga/mini-aspire/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// IUserRepository is an autogenerated mock type for the IUserRepository type
type IUserRepository struct {
	mock.Mock
}

// FindByUsername provides a mock function with given fields: username
func (_m *IUserRepository) FindByUsername(username string) (*auth.User, error) {
	ret := _m.Called(username)

	var r0 *auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.User, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.User); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreUser provides a mock function with given fields: user
func (_m *IUserRepository) StoreUser(user auth.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(auth.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUserRepository creates a new instance of IUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUserRepository(t mockConstructorTestingTNewIUserRepository) *IUserRepository {
	mock := &IUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
